### ISSUE TITLE
Unable to install package 1.4.1.1 from Nuget.

### ISSUE THREAD

**Issue by deipax** [MarcinJuraszek/CloneExtensions#15]
When attempting to update my 1.4.0 version to 1.4.1.1 I receive this error message:

Could not install package 'CloneExtensions 1.4.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact th
e package author.

Not sure what is happening.  I wanted to rerun my performance tests with the speed tweak for the dictionary used for circular references and compare.

**Comment by MarcinJuraszek** [comment]
Are you hitting the same issue when trying to update from `1.4.0` to `1.4.1`? The library started targeting net-standard 1.6 from that release.

**Comment by deipax** [comment]
I am primarily develop against the .Net Framework platform, so I never bothered keeping up to date with portable development.  After some reading this morning I came up to speed with .Net Standard and what would be required of me to consume the nuget package of the CloneExpression Library and its limitation for me needs.

For now, it is just easier for me to download the source compile my own consumables.  Sorry for the inconvenience, I will close this issue.
