### ISSUE TITLE
Multiple Frameworks

### ISSUE THREAD

**Issue by deipax** [MarcinJuraszek/CloneExtensions#20]
Marcin,

Currently, in version 1.4.1.1, the only target framework for which a library is built is for .NetStandard 1.6.   This is a restriction for any Nuget user that uses the .Net Framework, if someone is developing a library for their needs that uses anything other .NetStandard they can not add the package to their project for use.    It would seem that it would unnecessarily limit potential users.  Is this intended behavior?

-Jeff

**Comment by MarcinJuraszek** [comment]
Sorry, it's been a rather busy couple weeks for me. I'll take a look over the weekend and most likely bring .net4.5 target back.

**Comment by MarcinJuraszek** [comment]
You should be able to use it from .NET 4.5 and above with version [1.4.2](https://preview.nuget.org/packages/CloneExtensions/1.4.2). Let me know if you're still running into issues.

**Comment by deipax** [comment]
Marcin,
1.4.2 works as expected, thank you!  Do you know when you will have time to review the latest speed tweak?  After that one, I have one last tweak which leverages backing fields for automatic properties.

**Comment by MarcinJuraszek** [comment]
Looking into the other PR now!
